apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voter-api-hpa
  namespace: voter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voter-api
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    # Scale down quickly to save cost: once average CPU stays under 60% for about a minute --default 5min
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    # Scale up right away when load rises.
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
